#!/usr/bin/perl

use strict;
use warnings;

use File::Slurp qw(read_file);

sub judge_error {
  print "JUDGE-ERROR\n";
  exit;
}

sub slurp_canonical {
  my $result = read_file(shift, err_mode => 'carp') // die judge_error;

  # collapse whitespace and trim both ends
  $result =~ s/\s+/ /g;
  $result =~ s/^\s|\s$//g;

  return $result;
}

die judge_error unless @ARGV >= 2;

if (slurp_canonical($ARGV[0]) eq slurp_canonical($ARGV[1])) {
  print "OK\n";
} else {
  print "WRONG-ANSWER\n";
}
